### ISSUE TITLE
Inquiries about the code

### ISSUE THREAD

**Issue by MRrollingJerry** [hugochan/BAMnet#1]
Hi, I just read your paper and find it very interesting. I want to try running the code but it seems you haven't uploaded it yet. May I know if you have any update plan?

**Comment by hugochan** [comment]
@MRrollingJerry thank you for your attention! I am planning to release the code soon, say, before the NAACL2019 conference.

**Comment by MRrollingJerry** [comment]
Hi. Thanks for uploading the code! Could you upload the dataset that you have preprocessed and word2vec.npy to a google drive as well so we may run the code?

Could you explain what "delex_seed_15_fullvocab_plus" means?

**Comment by hugochan** [comment]
@MRrollingJerry yes. I will upload the data and add more instructions on how to run the code soon.

**Comment by hugochan** [comment]
@MRrollingJerry Please check out the updated readme for more instructions.
