### ISSUE TITLE
onedrive

### ISSUE THREAD

**Issue by xdcui-nlp** [hugochan/BAMnet#13]
Hello, I can't visit onedrive website. Can you provide data and models in other ways, such as Google drive

**Comment by hugochan** [comment]
> Hello, I can't visit onedrive website. Can you provide data and models in other ways, such as Google drive

@AdienQ Thank you for your interest to our work! As mentioned in the readme, if you cannot access the data and pretrained model from onedrive, please download them from [here](http://academic.hugochan.net/download/BAMnet-WebQ.zip).
