### ISSUE TITLE
can't find the data

### ISSUE THREAD

**Issue by fcc357** [hugochan/BAMnet#4]
the preprocessed data and the pretrained models can't be downloaded

**Comment by hugochan** [comment]
Hi @fcc357 , I just double checked it. The links are still valid. Could you please share the error messages you got when downloading those files?

**Comment by fcc357** [comment]
I can't access this web site without any prompt.
could you please send me a link to Baidunet 
disk?

**Comment by hugochan** [comment]
@fcc357 Sure, I will let you know when it is ready.

**Comment by fcc357** [comment]
Thank you  very much.

**Comment by remonly** [comment]
Hi, I can't access the website too, and it asks me to retry or refresh the website. Can I get your data and model link too? 
Also, I'm doing some research on multi-hop KBQA. I'm wondering if you have tested your model on multi-hop questions(1-3 hop), and how about the performance? Hope to hear your suggestions on adapting it to multi-hop KBQA.
Thank you for sharing your work.

**Comment by hugochan** [comment]
@fcc357 @remonly if you cannot access the data stored on OneDrive, please download from [here](http://academic.hugochan.net/download/BAMnet-WebQ.zip).

**Comment by hugochan** [comment]
> Hi, I can't access the website too, and it asks me to retry or refresh the website. Can I get your data and model link too?
> Also, I'm doing some research on multi-hop KBQA. I'm wondering if you have tested your model on multi-hop questions(1-3 hop), and how about the performance? Hope to hear your suggestions on adapting it to multi-hop KBQA.
> Thank you for sharing your work.

@remonly Thank you for your interest in our work! The WebQuestions data contains questions involving 1-2 hop reasoning. We have not tested the model on questions requiring more reasoning hops. However, nothing prevents running the model on multi-hop KBQA datasets. Happy to know how the model performs on other datasets.

**Comment by remonly** [comment]
Thank you for your kind reply. And If I got the result on my dataset, I would be happy to share that with you.
 
---Original---
