### ISSUE TITLE
Test on individual questions

### ISSUE THREAD

**Issue by AndrewAcomb** [hugochan/BAMnet#5]
Hello! Is there any support for testing the model on new questions after training it? If not, how would you recommend going about building that functionality? Ideally I would like to deploy the model as an API.

**Comment by hugochan** [comment]
> Hello! Is there any support for testing the model on new questions after training it? If not, how would you recommend going about building that functionality? Ideally I would like to deploy the model as an API.

Thank you for your interest to our work! It is doable but this functionality is not currently available. You will need to dynamically vectorize the input question and identify the topic entity, then feed them to the model. I am actually a bit busy recently. I will try implementing this in late Feb or early March. The topic entity identification is the most challenging one. The current model relies external tools for producing a list of candidates to select from.

**Comment by aorogat** [comment]
Hello. Is this issue solved? Can I feed your system by questions and get the answers?

**Comment by hugochan** [comment]
> Hello. Is this issue solved? Can I feed your system by questions and get the answers?

Unfortunately, I haven't implemented it yet. If you would like to try this quickly, please refer to this [example code](https://github.com/hugochan/PFoodReq/blob/master/BAMnet/src/run_online.py) which implemented an API called "answer" to do the job. Please let me know if you need any help regarding that.
