### ISSUE TITLE
Freebase .json.gz

### ISSUE THREAD

**Issue by hankcs** [hugochan/BAMnet#7]
Hi,

Thank you for your great work. I'm trying to run your code on FreebaseQA. Could you provide the `freebase key file`?

**Comment by hugochan** [comment]
> Hi,
> 
> Thank you for your great work. I'm trying to run your code on FreebaseQA. Could you provide the `freebase key file`?

Thank you for your attention to our work! Could you please tell me what the FreebaseQA is? We ran our experiments on WebQuestions whose underlying KB is Freebase. We only had Freebase keys that appear in WebQuestions.

**Comment by hankcs** [comment]
It's a new dataset: https://www.aclweb.org/anthology/N19-1028/

I'm trying to generate a `freebase_full.json` using your `run_freebase.py`, but I don't have the freebase gz files corresponding to this variable:

```
parser.add_argument('-fbkeys', '--freebase_keys', required=True, type=str, help='path to the freebase key file')
```

**Comment by hankcs** [comment]
> We only had Freebase keys that appear in WebQuestions.

Do you mean the Freebase keys are distributed with WebQuestions? Are they a small portion of freebase? That will be quite difficult for us to utilize your pre-processing scripts.

**Comment by hugochan** [comment]
> > We only had Freebase keys that appear in WebQuestions.
> 
> Do you mean the Freebase keys are distributed with WebQuestions? Are they a small portion of freebase? That will be quite difficult for us to utilize your pre-processing scripts.

Yes, WebQuestions only used a small portion of the whole Freebase since Freebase is a large KB. You might want to turn to the authors of FreebaseQA for help.

**Comment by hankcs** [comment]
Got it. Thank you.
