### ISSUE TITLE
IDs

### ISSUE THREAD

**Issue by zhiyuanw101** [hugochan/BAMnet#8]
Hi! just trying to transfer your model to another dataset and KB, for the file entity2id.json/ entityType2id.json/ relation2id.json, is there any restrictions on assigining their IDs? Or just assigining a distinct ID to each relation/entity is OK?

**Comment by hugochan** [comment]
> Hi! just trying to transfer your model to another dataset and KB, for the file entity2id.json/ entityType2id.json/ relation2id.json, is there any restrictions on assigining their IDs? Or just assigining a distinct ID to each relation/entity is OK?

Thank you for your attention to our work! Assigning a distinct ID should be fine.

**Comment by zhiyuanw101** [comment]
Thanks! Also, what are these IDs used for? What should I do for another Knowledge base to create such IDs files?

**Comment by hugochan** [comment]
> Thanks! Also, what are these IDs used for? What should I do for another Knowledge base to create such IDs files?

Some IDs (e.g., relation IDs) were used for learning embeddings, but some (e.g., entity IDs) were actually not used. You can simply assign some random IDs to distinguish different entities/relations/entity types.

**Comment by zhiyuanw101** [comment]
Thanks a lot! So if we just create a new set of IDs files from another KB in the same format of yours, than it should be able to train and test right?  Is there any possible extra work needed in the training/testing phase to fit in the data?
