### ISSUE TITLE
freebaseKeyCands is the entity linking results by using Freebase Search API?

### ISSUE THREAD

**Issue by bunnyfighting** [hugochan/BAMnet#9]
Hello! I download your dataste. The train/test/valid files (raw_train.json/raw_valid.json/raw_test.json) both contain the "freebaseKeyCands" data.  Where does the data "freebaseKeyCands" come from？ It is the entity linking results by using Freebase Search API ? Could you provide the entity linking results by using Freebase Search API for me ? Thanks a lot.

**Comment by hugochan** [comment]
> Hello! I download your dataste. The train/test/valid files (raw_train.json/raw_valid.json/raw_test.json) both contain the "freebaseKeyCands" data. Where does the data "freebaseKeyCands" come from？ It is the entity linking results by using Freebase Search API ? Could you provide the entity linking results by using Freebase Search API for me ? Thanks a lot.

@bunnyfighting Thank you for your interest to our work! The "freebaseKeyCands" field stores candidate topic entities from both Freebase Search API and S-MART, both of which are topic entity detection tools. Our proposed topic entity prediction module aims to predict the best topic entity from the candidate list. You can find information on how to get both Freebase Search API and S-MART results from [here](https://github.com/scottyih/STAGG/issues/1).

**Comment by bunnyfighting** [comment]
Thank you for your reply.  You provide very detailed information. Thanks a lot.

**Comment by bunnyfighting** [comment]
Hi, 
     In your paper, you use the Freebase Search API to get the F1 score of 0.497 in the test dataset. How much retrieval results do you use to test ?  The file "webquestions.examples.test.retrieved.json" contains the top 10 retrieval results for each test question using the Freebase Search API. Do you use the top 10 retrieval results for testing ? Thanks a lot.

**Comment by hugochan** [comment]
> Hi,
> In your paper, you use the Freebase Search API to get the F1 score of 0.497 in the test dataset. How much retrieval results do you use to test ? The file "webquestions.examples.test.retrieved.json" contains the top 10 retrieval results for each test question using the Freebase Search API. Do you use the top 10 retrieval results for testing ? Thanks a lot.

As for BAMnet w/ Freebase Search API, we used the top 1 result returned by Freebase Search API as the topic entity.
